version: '3.8'

services:
  mongo:
    image: mongo:3.6
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'unless-stopped'

  project:
    image: node:14
    working_dir: /workspace
    depends_on:
      - mongo
    environment:
      # cf: https://docs.mongodb.com/manual/reference/connection-string/
      MONGODB_URL: mongodb://mongo:27017/ts-distributed-lock-tests
    volumes:
      - .:/workspace:delegated
      - ~/.bash_history:/root/.bash_history
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'no'
