version: '3.7'

services:
  mongo:
    image: mongo:3.2
    ports:
      - 27017
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'unless-stopped'

  project:
    image: node:12
    depends_on:
      - mongo
    environment:
      # cf: https://docs.mongodb.com/manual/reference/connection-string/
      MONGODB_URL: mongodb://mongo:27017/ts-distributed-lock-tests

      YARN_CACHE_FOLDER: /var/cache/yarn
    working_dir: /workspace
    volumes:
      - .:/workspace:delegated
      - ~/.bash_history:/root/.bash_history
      - yarn_cache:/var/cache/yarn
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'no'

volumes:
  yarn_cache: ~
