name: CI

on: [push, pull_request]

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['12', '14']
        mongo: ['3.2', '3.6']
        include:
          - node: '12'
            mongo: '3.2'
            publish: true
            continue-on-error: false

    continue-on-error: ${{ matrix.continue-on-error == true }}

    container:
      image: node:${{ matrix.node }}

    services:
      mongodb:
        image: mongo:${{ matrix.mongo }}
        ports: [27017]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Yarn berry
        run: yarn set version berry

      - name: Validate dependencies
        run: yarn install --immutable --immutable-cache

      - name: Import Yarn plugins
        run: |
          yarn plugin runtime
          yarn plugin import @yarnpkg/plugin-version
          yarn plugin import @yarnpkg/plugin-workspace-tools

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test
        env:
          MONGODB_URL: mongodb://127.0.0.1:${{ job.services.mongodb.ports[27017] }}/ts-distributed-lock-tests

      - name: Publish to npmjs
        if: "matrix.publish == true && startsWith(github.ref, 'refs/tags/')"
        run: yarn run publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_AUTH_TOKEN }}
